# Generated by Django 5.1.1 on 2024-09-20 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='status',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a 10-digit mobile number')]),
        ),
    ]
