# Generated by Django 5.1.1 on 2024-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_item_status_supplier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
