# Generated by Django 5.1.1 on 2024-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_item_created_at_item_image_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='unknown address', max_length=500),
            preserve_default=False,
        ),
    ]
