# Generated by Django 5.1.1 on 2024-09-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_item_created_at_item_image_item_updated_at'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptable',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.item', unique=True),
        ),
    ]
