# Generated by Django 5.1.1 on 2024-09-30 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_temptable_item_id_salesmaster_salesdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestemptable',
            name='sales_master',
        ),
        migrations.AddField(
            model_name='salestemptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 30, 11, 58, 40, 528620)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestemptable',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
