# Generated by Django 5.1.1 on 2024-09-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_salestemptable_sales_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdetail',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='salestemptable',
            name='item_price',
        ),
    ]
