# Generated by Django 5.1.1 on 2024-10-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_supplier_address'),
        ('operations', '0004_remove_salesdetail_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptable',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.item'),
        ),
    ]
